1-Solution/SanaAssessment.Web/Controllers/ProductsController.cs
using SanaAssessment.Data.Model;
using SanaAssessment.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanaAssessment.Web.Controllers
{
    public class ProductsController : Controller
    {
        IProductRepositoryFactory _factory;
        RepositoryType _storageType;
        public ProductsController(IProductRepositoryFactory repositoryFactory)
        {
            _factory = repositoryFactory;
        }
        //
        // GET: /Products/
        public ActionResult Index()
        {
            var products = _factory.GetImplementation(_storageType).Get();
            return View(products);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Title,Price")]Product product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _factory.GetImplementation(_storageType).Insert(product);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ExceptionMessage = ex.Message;
                }
            }
            return View(product);
        }

        public ActionResult Edit(int id)
        {
            var product = _factory.GetImplementation(_storageType).GetById(id);
            if (product == null)
            {
                return new HttpNotFoundResult(string.Format("Product with id = {0} not found", id));
            }
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "Title,Price")]Product product)
        {
            if (ModelState.IsValid)
            {
                product.Id = id;
                try
                {
                    _factory.GetImplementation(_storageType).Update(product);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ExceptionMessage = ex.Message;
                }
            }
            return View(product);
        }

        public ActionResult Delete(int id)
        {
            var product = _factory.GetImplementation(_storageType).GetById(id);
            if (product == null)
            {
                return new HttpNotFoundResult(string.Format("Product with id = {0} not found", id));
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmDelete(int id)
        {
            var product = _factory.GetImplementation(_storageType).GetById(id);
            try
            {
                _factory.GetImplementation(_storageType).Delete(product);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ExceptionMessage = ex.Message;
            }
            return View(product);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            ResolveStorageType();
        }

        private void ResolveStorageType()
        {
            HttpCookie cookie = Request.Cookies["StorageType"];
            if (cookie != null)
            {
                RepositoryType stType;
                if (!Enum.TryParse<RepositoryType>(cookie.Value, out stType))
                {
                    stType = RepositoryType.InMemory;
                }
                _storageType = stType;
            }

            ViewBag.StorageType = _storageType;
        }
    }
}

1-Solution/SanaAssessment.Web/Controllers/StorageController.cs
using SanaAssessment.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanaAssessment.Web.Controllers
{
    public class StorageController : Controller
    {
        // GET: Storage
        public ActionResult Change(RepositoryType type)
        {
            var cookie = new HttpCookie("StorageType", type.ToString());
            cookie.Expires = DateTime.Now.AddYears(1);
            Response.Cookies.Add(cookie);

            return Redirect("/");
        }
    }
}

1-Solution/SanaAssessment.Web/Views/Products/Create.cshtml
@model SanaAssessment.Data.Model.Product

@{
    ViewBag.Title = "Add new Product";
}

<h3 class="text-muted">Create Product</h3>

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class="btn btn-primary" })
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default"/>
            </div>
        </div>
        
        @if (ViewBag.ExceptionMessage != null)
        {
        <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Failed!</strong>@ViewBag.ExceptionMessage
        </div>
        }
    </div>
}

@section bodyEnd
{
    <script type="text/javascript">
        setTimeout(function () { $(".alert").alert('close') }, 4000);
    </script>
}

1-Solution/SanaAssessment.Web/Views/Products/Delete.cshtml
@model SanaAssessment.Data.Model.Product

@{
    ViewBag.Title = "Delete Product";
}

<h3 class="text-muted">Delete Product</h3>

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>

<div class="col-md-offset-2 col-md-8">
    <h3>Are you sure you want to delete this product?</h3>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>@Model.Id</dd>

        <dt>Title</dt>
        <dd>@Model.Title</dd>

        <dt>Price</dt>
        <dd>@Model.Price</dd>
    </dl>
@using (Html.BeginForm("ConfirmDelete", "Products", new { Id = Model.Id }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })
    </div>
}
</div>

1-Solution/SanaAssessment.Web/Views/Products/Edit.cshtml
@model SanaAssessment.Data.Model.Product

@{
    ViewBag.Title = "Edit Product " + Model.Id;
}

<h3 class="text-muted">Edit Product</h3>

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>

<div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
        @if (ViewBag.ExceptionMessage != null)
        {
            <div class="alert alert-danger alert-dismissable col-md-offset-2 col-md-10">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Failed!</strong>@ViewBag.ExceptionMessage
            </div>
        }
    </div>
}   
</div>

@section bodyEnd
{
    <script type="text/javascript">
        setTimeout(function () { $(".alert").alert('close') }, 4000);
    </script>
}

1-Solution/SanaAssessment.Web/Views/Products/Index.cshtml
@model IEnumerable<SanaAssessment.Data.Model.Product>
@{
    ViewBag.Title = "Products";
}
<h3 class="text-muted">List of Products</h3>
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<section id="details">
    <table class="table">
        <tr>
            <th>Number</th>
            <th>Title</th>
            <th>Price</th>
            <th>&nbsp;</th>
        </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Title</td>
            <td>@item.Price</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { Id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { Id = item.Id }, new { data_delete = item.Id, data_toggle="confirmation", data_on_confirm="deleteProduct" })
            </td>
        </tr>
    }
    </table>
</section>

@section bodyEnd
{
}

1-Solution/SanaAssessment.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    Dictionary<SanaAssessment.Data.Repository.RepositoryType, String> storageTypes = new Dictionary<SanaAssessment.Data.Repository.RepositoryType, String>();
    storageTypes.Add(SanaAssessment.Data.Repository.RepositoryType.InMemory, "In Memory");
    storageTypes.Add(SanaAssessment.Data.Repository.RepositoryType.SqlCe, "SQL CE");
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @System.Web.Optimization.Styles.Render("~/Content/css")
</head>
<body>
    <nav class="nav navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Storage Type: @(storageTypes[ViewBag.StorageType]) <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @foreach (var pair in storageTypes)
                        {
                            if (ViewBag.StorageType != pair.Key)
                            {
                                <li>@Html.ActionLink(pair.Value, "Change", "Storage", new { type = pair.Key }, null)</li>
                            }
                        }
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    @System.Web.Optimization.Scripts.Render("~/bundles/bootstrap")
    @System.Web.Optimization.Scripts.Render("~/bundles/bootstrap_confirmation")
    @RenderSection("bodyEnd", required: false)
</body>
</html>